language: C
sudo: false
osx_image: xcode12.2
compiler:
  - gcc
  - clang
script:
  - make
  - make tests
addons:
  homebrew:
    packages:
      - lua
  apt:
    packages:
      - liblua5.2-dev
os:
  - linux
  - osx
